import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/components/Providers";
import { useSession } from "next-auth/react";
import { Provider } from "react-redux";
import store from "@/redux/store";
import { Toaster } from "react-hot-toast";


const inter = Inter({
  subsets: ["latin"]
});

export const metadata = {
  title: "aw2024",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <AuthProvider>

          {children}
          <Toaster />
        </AuthProvider>

      </body>
    </html>
  );
}
